upstream backend {
    # Mặc định là round-robin (lần lượt server1, server2, server1, ...)
    server server1:80;
    server server2:80;
    server server3:80 weight=3; # server2 sẽ được ưu tiên gấp 3 lần so với server1
    server server4:3000; # SSR thật - Next.js process sống, khác port với các server nginx còn lại

    # Muốn test kiểu "least connections" thì bỏ comment dòng dưới
    # least_conn;

    # Muốn sticky session theo IP client thì bỏ comment dòng dưới
    # ip_hash;

    random;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
